"""empty message

Revision ID: 90629743cd5c
Revises: eeaa722f392f
Create Date: 2022-06-03 11:46:36.384510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90629743cd5c'
down_revision = 'eeaa722f392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
